Fixes type definition of column 'theme' in table 'instance'
Error message:
sqlalchemy.exc.CompileError: (in table 'instance', column 'theme'): VARCHAR requires a length on dialect mysql